import "./globals.css";
import Header from "@/components/Header"

export const metadata = {
  title: "Site Fernanda",
  description: "Generated by Fernanda",
  charset: 'UTF-8',
  author: 'Fernanda',
  keywords: 'HTML, CSS, JavaScript, React, Next.js'
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
