// import localFont from "next/font/local";
import "./globals.css";

export const metadata = {
  title: "Minha primeira aplicação",
  description: "Generated by Fernanda",
  charset: 'UTF-8',
  author: 'Fernanda',
  keywords: 'HTML, CSS, JavaScript, React, Next.js'
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body>
        {children}
      </body>
    </html>
  );
}